# _config.yml
plugins:
  - jekyllâ€mathjax

mathjax:
  tex_extensions: ["AMSmath.js", "AMSsymbols.js"]
  inline_delimiters:
    - ["\\(", "\\)"]
    - ["$", "$"]
  display_delimiters:
    - ["\\[", "\\]"]
    - ["$$", "$$"]
